# Generated by Django 4.1.7 on 2023-10-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
