# Generated by Django 4.1.7 on 2023-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_vendedor'),
        ('agenda', '0002_delete_viaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nit',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
    ]
