# Generated by Django 4.1.7 on 2023-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
